### ISSUE TITLE
I2c support

### ISSUE THREAD

**Issue by DaveDischord** [avollkopf/cbpi4-pt100x#11]
Not an issue, but more of a request or guidance.  I have the Sparkfin Quiic version [here](https://www.sparkfun.com/products/retired/16770)

How can I go about utilizing your plug-in to work with it?

Thanks!

**Comment by avollkopf** [comment]
I just took a quick look at the link, you shared. Unfortunately, the device is already 'retired' and not available anymore. In addition to that, I was not able to find any python libraries to read out the ADC via I2C. I have no real hope, that this will end up in a plugin.

**Comment by avollkopf** [comment]
As the device is not available anymore and no python libraries available, issue will be closed
