### ISSUE TITLE
Transmission of values from a PT100 to Influx

### ISSUE THREAD

**Issue by userbasti** [avollkopf/cbpi4-pt100x#9]
If a pt100 temperature sensor is connected, the value is displayed correctly in CBPi but not passed on to Influx. Values from connected DS18B20 sensors are transmitted correctly. Values from a PT100 sensor connected via MQTTDevice are also transmitted.

**Comment by avollkopf** [comment]
Please post a screenshot of your hardware sensor config. Did you define a kettle or fermenter in the config for the sensor? In this case it logs only data when the kettle/fermenter is active.

**Comment by userbasti** [comment]
Now it works. It was because I had already assigned the sensor to the Kettle. I didn't know that it would only start when the Kettle was active. Many thanks for the quick help.
